package com.kogon.selenium.gridmonitor.views;


import javax.swing.JList;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author developer
 */
public class ConnectionMonitorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConnectionMonitorPanel
     */
    public ConnectionMonitorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theConnectionRequestListScrollPane = new javax.swing.JScrollPane();
        theConnectionRequestList = new javax.swing.JList();

        theConnectionRequestList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        theConnectionRequestListScrollPane.setViewportView(theConnectionRequestList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(theConnectionRequestListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(theConnectionRequestListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList theConnectionRequestList;
    private javax.swing.JScrollPane theConnectionRequestListScrollPane;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JList getConnectionRequestList() {
		return theConnectionRequestList;
	}

	public void setConnectionRequestList(javax.swing.JList aConnectionRequestList) {
		theConnectionRequestList = aConnectionRequestList;
	}

	public javax.swing.JScrollPane getConnectionRequestListScrollPane() {
		return theConnectionRequestListScrollPane;
	}

	public void setConnectionRequestListScrollPane(
			javax.swing.JScrollPane aConnectionRequestListScrollPane) {
		theConnectionRequestListScrollPane = aConnectionRequestListScrollPane;
	}

}
