/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.kogon.selenium.gridmonitor.views;

/**
 *
 * @author developer
 */
public class RegistrationRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationRequestPanel
     */
    public RegistrationRequestPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theSplitPane = new javax.swing.JSplitPane();
        jScroll1 = new javax.swing.JScrollPane();
        theTextArea = new javax.swing.JTextArea();
        jScroll2 = new javax.swing.JScrollPane();
        theTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        theSplitPane.setDividerLocation(300);
        theSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        theTextArea.setColumns(20);
        theTextArea.setRows(5);
        jScroll1.setViewportView(theTextArea);

        theSplitPane.setBottomComponent(jScroll1);

        theTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScroll2.setViewportView(theTable);

        theSplitPane.setLeftComponent(jScroll2);

        add(theSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScroll1;
    private javax.swing.JScrollPane jScroll2;
    private javax.swing.JSplitPane theSplitPane;
    private javax.swing.JTable theTable;
    private javax.swing.JTextArea theTextArea;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JScrollPane getjScroll1() {
		return jScroll1;
	}

	public javax.swing.JScrollPane getjScroll2() {
		return jScroll2;
	}

	public javax.swing.JSplitPane getSplitPane() {
		return theSplitPane;
	}

	public javax.swing.JTable getTable() {
		return theTable;
	}

	public javax.swing.JTextArea getTextArea() {
		return theTextArea;
	}
}
